#!/usr/bin/env python3
"""Build site/js/config.js from secrets.json or secrets.example.json."""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
SECRETS = ROOT / "secrets.json"
EXAMPLE = ROOT / "secrets.example.json"
OUT = ROOT / "site" / "js" / "config.js"

source = SECRETS if SECRETS.exists() else EXAMPLE
data = json.loads(source.read_text(encoding="utf-8"))
aff = data.get("affiliates", {})

js = f"""// Generated by scripts/build-config.py — edit secrets.json locally
window.MONEY_CONFIG = {{
  amazonTag: "{data.get("amazon_associate_tag", "")}",
  affiliates: {{
    invoicing: "{aff.get("invoicing", "")}",
    budgeting: "{aff.get("budgeting", "")}",
    savings: "{aff.get("savings", "")}",
    credit: "{aff.get("credit", "")}"
  }},
  donateUrl: "{data.get("donate_url", "")}",
  premiumUrl: "{data.get("premium_stripe_url", "")}"
}};
"""

OUT.write_text(js, encoding="utf-8")
print(f"Wrote {OUT}")
