param(
    [string]$Root = (Split-Path -Parent $PSScriptRoot)
)

$secretsPath = Join-Path $Root "secrets.json"
$examplePath = Join-Path $Root "secrets.example.json"
$linksPath = Join-Path $Root "site\links.js"

if (-not (Test-Path $secretsPath)) {
    Copy-Item $examplePath $secretsPath
    Write-Host "Created secrets.json from example. Edit affiliate links there."
}

$secrets = Get-Content $secretsPath -Raw | ConvertFrom-Json
$aff = $secrets.affiliates
$form = $secrets.email_capture.formspree_endpoint
$ig = $secrets.instagram_handle

$js = @"
// Auto-generated by scripts/sync-site.ps1 — edit secrets.json instead
window.SITE_LINKS = {
  guide: "$($aff.free_guide_url)",
  savings: "$($aff.high_yield_savings)",
  budget: "$($aff.budget_app)",
  card: "$($aff.credit_card)",
  formEndpoint: "$form",
  instagram: "$ig"
};
"@

Set-Content -Path $linksPath -Value $js -Encoding UTF8
Write-Host "Synced site/links.js from secrets.json"
